Fix commands
RebelMythik/AntiVillagerLag pull request #28
Opened 2022-08-02 21:34 UTC by PhoenixZTT

Change weird if else code to a more proper way of doing commands

2022-08-03 08:34 UTC, D-VR commented
I like the clearNametag functionality, would it make sense to not have a specific name but instead have it be a boolean config option which clears the name if a villager gets disabled again?

2022-08-03 08:37 UTC, D-VR commented
I can do this change + add other small fixes to this PR or a later PR

(if y'all agree to the boolean config option)

2022-08-03 09:36 UTC, PhoenixZTT commented
> I like the clearNametag functionality, would it make sense to not have a specific name but instead have it be a boolean config option which clears the name if a villager gets enabled again?

Maybe even using PDC to store the old name a restore it to that

2022-08-03 16:13 UTC, D-VR commented
hmh.. yes would need to add setter getter and has for it, not too bad though

2022-08-14 18:57 UTC, RebelMythik requested changes
will pull when its fixed

2022-08-14 18:57 UTC, RebelMythik commented on src/main/java/rebelmythik/antivillagerlag/commands/RadiusOptimizeCommand.java
> +                sender.sendMessage(colorcodes.cm("&aOptimized "+count+" villagers!"));
Make the message not hard coded

2022-08-14 18:57 UTC, RebelMythik commented on src/main/java/rebelmythik/antivillagerlag/AntiVillagerLag.java
> +        ColorCode colorcodes = new ColorCode();
Not going to set permissions here. They are already in plugin.yml

2022-09-20 19:08 UTC, closed without merging